alert('Hello');
document.querySelector('h1').innerHTML = "Changed";
document.querySelector("h1").classList.toggle("invisible");
document.querySelector("h1").classList.toggle("invisible");
document.querySelector("h1").classList.toggle("invisible");
document.querySelector("h1").classList.toggle("invisible");


document.querySelector("input").click();
document.querySelector("input").click();
document.getElementById("list").style.color = red;
document.getElementById("list").style.color = "red";
document.getElementById("list").style.color = "blue";
document.getElementsByTagName("li");
document.getElementsByTagName("li")[1].style.color = "green";
document.getElementsByTagName("li")[1].style.color = "light green";
document.getElementsByTagName("li").length;
document.getElementsByClassName("btn");
document.querySelector(".btn");
document.querySelector("#list");
typeof(document.querySelector("#list"));
typeof(document.querySelector(".btn"));
typeof(document.getElementsByClassName("btn"));
document.querySelector("ul li");
document.querySelectorAll("ul li");
document.querySelector("body.btn");
document.querySelector("button.btn");
document.querySelector("button");
document.querySelector("#list li");
document.querySelectorAll("#list li");
document.querySelectorAll("#list li").innerHTML;
document.querySelector("#list li").innerHTML;
document.querySelector(".btn").style.backgroundColor = "yellow";
document.querySelector("button").classList;
document.querySelector(".btn").classList;
document.querySelector("button").classList.add("invisible");
document.querySelector("button").classList.remove("invisible");
document.querySelector("button").classList.toggle("invisible");
document.querySelector("li").innerHTML;
document.querySelector("li").textContent;
document.querySelector("h1").innerHTML = "<em>Hello</em>";
document.querySelector("h1").textContent = "<em>Changed</em>";
document.querySelector("a").attributes;
document.querySelector("a").getAttribute("href");
document.querySelector("a").setAttribute("href", "#");
document.querySelector(".btn").getAttribute("class");

